import assert from "node:assert/strict";
import { mkdtemp, readFile, stat, rm, symlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { once } from "node:events";
import test from "node:test";
import { saveJevKey } from "../../../src/app/control/jev-settings.js";
import { createControlServer } from "../../../src/app/control/server.js";
import { writeFile } from "node:fs/promises";

test("Jev credential lifecycle is private and never returns the key", async (t) => {
  const previous = process.env.TYPESAFE_API_KEY;
  delete process.env.TYPESAFE_API_KEY;
  t.after(() => { if (previous !== undefined) process.env.TYPESAFE_API_KEY = previous; });
  const directory = await mkdtemp(join(tmpdir(), "jev-settings-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const keyPath = join(directory, "credentials/key");
  const configPath = join(directory, "router.toml");
  await writeFile(configPath, `version = 3\n[classifier]\napi_key_file = ${JSON.stringify(keyPath)}\n[logging]\naudit_file = ${JSON.stringify(join(directory, "audit"))}\n`);
  const server = createControlServer({ configPath, version: "test", host: "127.0.0.1", port: 0 });
  server.listen(0, "127.0.0.1");
  await once(server, "listening");
  t.after(() => server.close());
  const address = server.address();
  assert(address && typeof address === "object");
  const url = `http://127.0.0.1:${address.port}/v1/jev/key`;
  const key = "apikey_synthetic_test_credential_only";
  const blocked = await fetch(url, { method: "PUT", headers: { Origin: "https://untrusted.example" }, body: JSON.stringify({ key }) });
  assert.equal(blocked.status, 403);
  const saved = await fetch(url, { method: "PUT", body: JSON.stringify({ key }) });
  assert.equal(saved.status, 200);
  const text = await saved.text();
  assert.equal(text.includes(key), false);
  assert.deepEqual(JSON.parse(text).jev, { configured: true, source: "file" });
  assert.equal((await stat(keyPath)).mode & 0o777, 0o600);
  assert.equal((await stat(join(directory, "credentials"))).mode & 0o777, 0o700);
  const invalid = await fetch(url, { method: "PUT", body: JSON.stringify({ key: "invalid-secret" }) });
  assert.equal(invalid.status, 400);
  assert.equal(await readFile(keyPath, "utf8"), `${key}\n`);
  const removed = await fetch(url, { method: "DELETE" });
  assert.equal(removed.status, 200);
  assert.equal((await removed.json()).jev.configured, false);
  assert.equal((await fetch(url, { method: "DELETE" })).status, 200);
  const link = join(directory, "link");
  await symlink(directory, link);
  await assert.rejects(saveJevKey(join(link, "unsafe"), key), /符号链接/);
});
